package com.opencasino.server.security

enum class AuthFailureCode {
    INVALID_EMAIL,
    WEAK_PASSWORD,
    INVALID_DISPLAY_NAME,
    MALFORMED_REQUEST,
    EMAIL_TAKEN,
    INVALID_CREDENTIALS,
    OAUTH_EMAIL_UNVERIFIED,
    OAUTH_PROVIDER_ERROR,
    REFRESH_INVALID,
    REFRESH_EXPIRED,
    REFRESH_REVOKED,
    REFRESH_REPLAY_DETECTED,
}
