spring.application.name=openCasino_server

spring.devtools.livereload.enabled=false

server.port=8080

spring.config.import=classpath:/database.properties
#.classpath:/auth.properties
#,classpath:ssl.properties
